name: analysis
channels:
- conda-forge
dependencies:
- conda-forge::python=3.8.5
- conda-forge::pandas=1.1.3
- conda-forge::numpy=1.19.2
- conda-forge::pathlib=1.0.1
- conda-forge::jupyter=1.0.0
- conda-forge::ipykernel=5.3.4
- conda-forge::tabulate=0.8.7
- conda-forge::seaborn=0.11.0
- conda-forge::matplotlib=3.3.2
- conda-forge::xlrd==1.2.0
- conda-forge::plotly=4.14.3
- conda-forge::plotly-orca=1.3.1
- conda-forge::psutil=5.8.0
- conda-forge::requests=2.25.1
- conda-forge::scipy=1.5.2
- conda-forge::kneed=0.7.0
