name: profiling
dependencies:
- conda-forge::python=3.7.1
- conda-forge::pandas=1.2.0
- conda-forge::pip=19.2.2
- conda-forge::pyyaml=5.3.1
- conda-forge::plotly=4.14.3
- plotly::python-kaleido=0.0.3
- pip
- pip:
  - git+https://github.com/cytomining/pycytominer@36241269c4293c24484986568ca16b2d7eb9e808
